[freent.kernelmodule.info]
name = "Win32 on OpenWindows"
description = "Run most Microsoft Windows applications in OpenWindows."
antiFeatures = {"non-free-deps"}
setupScripts = {"download-dlls"}
scripts = {"vm"}
